version: "3.9"
services:

#=========== Generic multiple sensor monitoring =====
 generic-multiple-sensors:
      container_name: Sensors
      image: generic_multiple_signal_monitor_mqtt_img:0.0.1
      restart: always
      volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
      env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
      environment:
            LINE_NAME: ${LINE_NAME}
            MACHINE_NAME: "device01"
      labels:
            IoT.container.project: "IoT_Industrial"
      networks:
            - IOT_Network

 sensor01-anomaly-detect:
       container_name: Sensor01-Anomaly
       image: single_signal_anomaly_detect_zscore_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "DiffPressSensor1"
              Z_SCORE_THRESHOLD: 2.5
       labels:
              IoT.container.project: "IoT_Industrial"
              
       networks:
              - IOT_Network


# ===== Generic multiple state monitoring ====

 generic-multiple-state:
       container_name: States
       image: generic_multiple_state_monitor_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
       labels:
              IoT.container.project: "IoT_Industrial"
              
       networks:
              - IOT_Network 


# ===== Vibration acceleration monitoring ====

 vib-accel-monitor-01:
       container_name: VibAccelMonitor01
       image: vib_anomaly_detect_z_score_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 2.7
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "Vib1"

       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


 vib-accel-monitor-02:
       container_name: VibAccelMonitor02
       image: vib_anomaly_detect_z_score_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 3.0
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "Vib2"

       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


 vib-accel-monitor-03:
       container_name: VibAccelMonitor03
       image: vib_anomaly_detect_z_score_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 3.0
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "Vib3"

       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


 vib-accel-monitor-04:
       container_name: VibAccelMonitor04
       image: vib_anomaly_detect_z_score_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 3.0
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "Vib4"

       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


 vib-accel-monitor-05:
       container_name: VibAccelMonitor05
       image: vib_anomaly_detect_z_score_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 2.5
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "Vib5"

       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


 vib-accel-monitor-06:
       container_name: VibAccelMonitor06
       image: vib_anomaly_detect_z_score_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 2.5
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "Vib6"

       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network




# ===== Air valve analytics  ====

 air-valve-monitor-01:
       container_name: AirValveMonitor01
       image: air_valve_zscore_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 2.5
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "AirValve1"
       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


 air-valve-monitor-02:
       container_name: AirValveMonitor02
       image: air_valve_zscore_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 3.0
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "AirValve2"
       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


 air-valve-monitor-03:
       container_name: AirValveMonitor03
       image: air_valve_zscore_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 3.0
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "AirValve3"
       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


 air-valve-monitor-04:
       container_name: AirValveMonitor04
       image: air_valve_zscore_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              Z_SCORE_THRESHOLD: 3.0
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              SENSOR_NAME: "AirValve4"
       labels:
              IoT.container.project: "IoT_Industrial"
       networks:
              - IOT_Network


# ===== Electrical anomaly analytics for one device====

 electrical-analytics1:
       container_name: ElecDevice1
       image: electrical_analytics_z_score_mqtt_img:0.0.1
       restart: always
       volumes:
              - "/etc/timezone:/etc/timezone:ro"
              - "/etc/localtime:/etc/localtime:ro"
       env_file:
              - ./mqtt_settings.env
              - ./influxdb_settings.env
       environment:
              MODEL_WINDOW_SIZE: ${MODEL_WINDOW_SIZE}
              ANOMALY_LIST_SIZE: ${ANOMALY_LIST_SIZE}
              CURRENT_PEAK_NUMBER: 1
              CURRENT_PEAK_HEIGHT: 1.3
              Z_SCORE_THRESHOLD: 3.0
              LINE_NAME: ${LINE_NAME}
              MACHINE_NAME: "device01"
              DEVICE_NAME : "ElecDevice1"
       labels:
              IoT.container.project: "IoT_Industrial"
              
       networks:
              - IOT_Network



# ===== NETWORK CONFIG ================

# network is created outside of docker-compose: 
networks:
  IOT_Network:
     external: true






